const KEY='cei-barra-content-v3'; const DEFAULT={heroTitle:'Uma igreja para viver a presença de Deus em comunidade.',heroText:'Seja bem-vindo à CEI Barra. Um lugar para adorar, aprender, servir e caminhar junto.',address:'Rua Aristóbulo Pelodan, 499',city:'Barra de São João • Casimiro de Abreu/RJ',phone:'(22) 99999-9999',email:'contato@ceibarra.org.br',instagram:'https://www.instagram.com/ceibarraoficial',youtube:'https://www.youtube.com/@CeiBarra',facebook:'https://www.facebook.com/ceibsj',services:[{day:'DOMINGO',time:'18:00',title:'Culto de Celebração',description:'Um tempo de louvor, Palavra e comunhão para toda a família.',location:'CEI Barra',active:true},{day:'QUARTA',time:'19:30',title:'Culto da Palavra',description:'Uma noite para aprofundar a fé e crescer no conhecimento da Palavra.',location:'CEI Barra',active:true},{day:'SEXTA',time:'19:30',title:'Encontro de Oração',description:'Momento de intercessão, cuidado e busca pela presença de Deus.',location:'CEI Barra',active:true}],events:[{date:'18',month:'OUT',title:'Celebração em família',description:'Uma noite especial de louvor e comunhão.',image:'cei-celebracao.jpg',active:true},{date:'25',month:'OUT',title:'Encontro da comunidade',description:'Um momento para estar juntos e fortalecer vínculos.',image:'cei-mulheres.jpg',active:true}]};
function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return DEFAULT}} function save(){localStorage.setItem(KEY,JSON.stringify(state));}
let state=load(), tab='dashboard';
const login=document.getElementById('login'), app=document.getElementById('app');
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault(); if(document.getElementById('user').value==='admin' && document.getElementById('pass').value==='cei2026'){sessionStorage.setItem('cei-admin','1');login.classList.add('hidden');app.classList.remove('hidden');render()} else alert('Usuário ou senha inválidos.')});
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('cei-admin');location.reload()};
document.getElementById('save').onclick=()=>{save();alert('Alterações salvas neste navegador.')};
if(sessionStorage.getItem('cei-admin')){login.classList.add('hidden');app.classList.remove('hidden')}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
function render(){const titles={dashboard:'Visão geral',home:'Página inicial',services:'Programação',events:'Eventos',prayers:'Pedidos de oração'};document.getElementById('tabTitle').textContent=titles[tab];const panel=document.getElementById('panel');
if(tab==='dashboard'){const req=JSON.parse(localStorage.getItem('cei-barra-prayer-requests')||'[]');panel.innerHTML=`<div class="panelGrid"><div class="stat"><span>HORÁRIOS ATIVOS</span><b>${state.services.filter(x=>x.active).length}</b></div><div class="stat"><span>EVENTOS ATIVOS</span><b>${state.events.filter(x=>x.active).length}</b></div><div class="stat"><span>PEDIDOS DE ORAÇÃO</span><b>${req.length}</b></div></div><div class="card" style="margin-top:16px"><h2>Bem-vindo ao painel</h2><p>Use o menu para atualizar a programação, eventos e os textos da página inicial. Os dados desta versão são salvos no navegador.</p></div>`}
if(tab==='home'){panel.innerHTML=`<div class="card"><h2>Apresentação</h2><div class="formgrid"><div class="field"><label>Título principal</label><textarea id="heroTitle">${esc(state.heroTitle)}</textarea></div><div class="field"><label>Texto</label><textarea id="heroText">${esc(state.heroText)}</textarea></div><div class="field"><label>Endereço</label><input id="address" value="${esc(state.address)}"></div><div class="field"><label>Cidade / estado</label><input id="city" value="${esc(state.city)}"></div><div class="field"><label>Telefone</label><input id="phone" value="${esc(state.phone)}"></div><div class="field"><label>E-mail</label><input id="email" value="${esc(state.email)}"></div><div class="field"><label>Instagram</label><input id="instagram" value="${esc(state.instagram)}"></div><div class="field"><label>YouTube</label><input id="youtube" value="${esc(state.youtube)}"></div><div class="field"><label>Facebook</label><input id="facebook" value="${esc(state.facebook)}"></div></div></div>`; bindFields(['heroTitle','heroText','address','city','phone','email','instagram','youtube','facebook'])}
if(tab==='services'){panel.innerHTML=`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2>Programação</h2><p>Cadastre os encontros exibidos no site.</p></div><button class="save" onclick="addService()">Novo horário</button></div>${state.services.map((s,i)=>`<div class="row"><div><b>${esc(s.title)}</b><div style="color:#6f7a74">${esc(s.day)} · ${esc(s.time)} · ${esc(s.location)}</div></div><div class="actions"><button class="smallbtn" onclick="toggleService(${i})">${s.active?'Ocultar':'Ativar'}</button><button class="smallbtn danger" onclick="delService(${i})">Excluir</button></div></div>`).join('')}</div>`}
if(tab==='events'){panel.innerHTML=`<div class="card"><div style="display:flex;justify-content:space-between;align-items:center"><div><h2>Eventos</h2><p>Cadastre os eventos exibidos no site.</p></div><button class="save" onclick="addEvent()">Novo evento</button></div>${state.events.map((e,i)=>`<div class="row"><div><b>${esc(e.title)}</b><div style="color:#6f7a74">${esc(e.date)} ${esc(e.month)}</div></div><div class="actions"><button class="smallbtn" onclick="toggleEvent(${i})">${e.active?'Ocultar':'Ativar'}</button><button class="smallbtn danger" onclick="delEvent(${i})">Excluir</button></div></div>`).join('')}</div>`}
if(tab==='prayers'){const req=JSON.parse(localStorage.getItem('cei-barra-prayer-requests')||'[]');panel.innerHTML=`<div class="card"><h2>Pedidos de oração</h2><p>Mensagens recebidas pelo formulário do site.</p>${req.length?req.map((r,i)=>`<article class="prayerItem"><b>${esc(r.name||'Sem nome')}</b><small>${new Date(r.createdAt).toLocaleString('pt-BR')}</small><p>${esc(r.message)}</p><span style="color:#6f7a74">${esc(r.contact||'Sem contato')}</span></article>`).join(''):'<p>Nenhum pedido recebido.</p>'}</div>`}
}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function bindFields(keys){keys.forEach(k=>document.getElementById(k).addEventListener('input',e=>state[k]=e.target.value))}
window.addService=()=>{state.services.push({day:'DOMINGO',time:'19:00',title:'Novo encontro',description:'Descreva este encontro.',location:'CEI Barra',active:true});render()};window.toggleService=i=>{state.services[i].active=!state.services[i].active;save();render()};window.delService=i=>{if(confirm('Excluir este horário?')){state.services.splice(i,1);save();render()}};
window.addEvent=()=>{state.events.push({date:'01',month:'NOV',title:'Novo evento',description:'Descrição do evento.',image:'cei-galeria.jpg',active:true});render()};window.toggleEvent=i=>{state.events[i].active=!state.events[i].active;save();render()};window.delEvent=i=>{if(confirm('Excluir este evento?')){state.events.splice(i,1);save();render()}};
render();
