const KEY='cei-barra-site-v4';
const DEFAULT={speakers:[{id:'sp1',name:'Próximo pregador',date:'DOMINGO • 18H',note:'Cadastre o convidado no painel',image:'cei-palavra.jpg',active:true}],services:[{id:'sv1',day:'DOMINGO',time:'18:00',title:'Culto de Celebração',description:'Louvor, Palavra e comunhão para toda a família.',location:'CEI Barra',active:true}],events:[{id:'ev1',day:'18',month:'OUT',title:'Celebração em família',description:'Uma noite especial para estarmos juntos.',active:true}],settings:{heroTitle:'Uma igreja para\npertencer.',heroText:'Um lugar para adorar a Deus, ouvir a Palavra e caminhar com pessoas de verdade.',address:'Rua Aristóbulo Pelodan, 499',city:'Barra de São João • Casimiro de Abreu/RJ',phone:'(22) 99999-9999',email:'contato@ceibarra.org.br',instagram:'https://www.instagram.com/ceibarraoficial',youtube:'https://www.youtube.com/@CeiBarra',facebook:'https://www.facebook.com/ceibsj'}};
let state=load();let tab='dashboard';let editIndex=null;
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');const s={...DEFAULT,...(saved||{})};s.settings={...DEFAULT.settings,...(saved?.settings||{})};return s}catch{return structuredClone(DEFAULT)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
const login=document.getElementById('login'),app=document.getElementById('app');
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();if(user.value==='admin'&&pass.value==='cei2026'){sessionStorage.setItem('cei-admin','1');login.classList.add('hidden');app.classList.remove('hidden');render()}else alert('Usuário ou senha inválidos.')});
if(sessionStorage.getItem('cei-admin')){login.classList.add('hidden');app.classList.remove('hidden')}
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('cei-admin');location.reload()};
document.getElementById('saveAll').onclick=()=>{persist();toast('Alterações salvas neste navegador.')};
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
function toast(msg){const old=document.querySelector('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;Object.assign(t.style,{position:'fixed',right:'22px',bottom:'22px',background:'#214f3a',color:'#fff',padding:'13px 16px',borderRadius:'10px',zIndex:100,fontWeight:800});document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function asset(s){return String(s||'').startsWith('data:')?s:`./images/${s}`}
function render(){document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const names={dashboard:'Visão geral',home:'Página inicial',speakers:'Pregadores',services:'Cultos',events:'Eventos',prayers:'Pedidos de oração',backup:'Backup'};document.getElementById('title').textContent=names[tab];const p=document.getElementById('panel');p.innerHTML='';if(tab==='dashboard')return dashboard(p);if(tab==='home')return home(p);if(tab==='speakers')return speakers(p);if(tab==='services')return services(p);if(tab==='events')return events(p);if(tab==='prayers')return prayers(p);if(tab==='backup')return backup(p)}
function dashboard(p){const req=JSON.parse(localStorage.getItem('cei-barra-prayer-requests')||'[]');p.innerHTML=`<div class="grid3"><div class="stat"><span>PRELETORES ATIVOS</span><strong>${state.speakers.filter(x=>x.active).length}</strong></div><div class="stat"><span>CULTOS ATIVOS</span><strong>${state.services.filter(x=>x.active).length}</strong></div><div class="stat"><span>PEDIDOS DE ORAÇÃO</span><strong>${req.length}</strong></div></div><div class="grid2" style="margin-top:16px"><div class="card"><h2>Conteúdo rápido</h2><p>O novo painel permite administrar a agenda dos pregadores, cultos, eventos e dados exibidos no site.</p><div class="toolbar"><button class="outline" onclick="switchTab('speakers')">Gerenciar pregadores</button><button class="outline" onclick="switchTab('events')">Gerenciar eventos</button></div></div><div class="card"><h2>Como funciona</h2><p>As alterações desta versão são salvas no navegador. Use <strong>Backup</strong> para exportar/importar os dados entre computadores.</p></div></div>`}
function home(p){p.innerHTML=`<div class="card"><h2>Conteúdo principal e contato</h2><div class="grid2"><div class="field"><label>Título principal</label><textarea id="heroTitle">${esc(state.settings.heroTitle||'Uma igreja para\npertencer.')}</textarea></div><div class="field"><label>Texto principal</label><textarea id="heroText">${esc(state.settings.heroText||'')}</textarea></div><div class="field"><label>Endereço</label><input id="address" value="${esc(state.settings.address||'')}"></div><div class="field"><label>Cidade / região</label><input id="city" value="${esc(state.settings.city||'')}"></div><div class="field"><label>Telefone</label><input id="phone" value="${esc(state.settings.phone)}"></div><div class="field"><label>E-mail</label><input id="email" value="${esc(state.settings.email)}"></div><div class="field"><label>Instagram</label><input id="instagram" value="${esc(state.settings.instagram)}"></div><div class="field"><label>YouTube</label><input id="youtube" value="${esc(state.settings.youtube)}"></div><div class="field"><label>Facebook</label><input id="facebook" value="${esc(state.settings.facebook)}"></div></div><div class="toolbar" style="margin-top:18px"><button class="save" onclick="saveHome()">Salvar esta seção</button></div></div><div class="card" style="margin-top:16px"><h2>O que você pode administrar agora</h2><p class="hint">Pregadores do carrossel, imagens, cultos, eventos, contatos, redes sociais e pedidos de oração. O backup permite levar esse conteúdo para outro computador.</p></div>`}
window.saveHome=()=>{['heroTitle','heroText','address','city','phone','email','instagram','youtube','facebook'].forEach(k=>state.settings[k]=document.getElementById(k).value);persist();toast('Dados da home salvos.');}
function speakers(p){const arr=state.speakers;p.innerHTML=`<div class="toolbar"><div><h2>Próximos pregadores</h2><div class="hint">Cadastre nome, data, descrição e uma imagem. O carrossel da home será atualizado.</div></div><button class="save" onclick="newSpeaker()">+ Novo pregador</button></div><div class="grid2">${arr.length?arr.map((s,i)=>`<article class="item"><div>${s.image?`<img src="${asset(esc(s.image))}" alt="">`:`<div class="thumb">CEI</div>`}</div><div class="meta"><strong>${esc(s.name)}</strong><span>${esc(s.date)} • ${s.active?'Visível':'Oculto'}</span><p class="hint">${esc(s.note||'')}</p></div><div class="row-actions"><button class="mini" onclick="moveSpeaker(${i},-1)">↑</button><button class="mini" onclick="moveSpeaker(${i},1)">↓</button><button class="mini" onclick="editSpeaker(${i})">Editar</button><button class="mini" onclick="toggleSpeaker(${i})">${s.active?'Ocultar':'Ativar'}</button><button class="mini danger" onclick="removeSpeaker(${i})">Excluir</button></div></article>`).join(''):'<div class="empty">Nenhum pregador cadastrado.</div>'}</div>`}
window.newSpeaker=()=>{editIndex=null;openSpeakerForm()};window.editSpeaker=i=>{editIndex=i;openSpeakerForm(state.speakers[i])};
function openSpeakerForm(s={name:'',date:'DOMINGO • 18H',note:'',image:'',active:true}){const p=document.getElementById('panel');p.innerHTML=`<div class="card"><div class="toolbar"><div><h2>${editIndex===null?'Novo pregador':'Editar pregador'}</h2><div class="hint">Esta imagem será exibida no carrossel da página inicial.</div></div><button class="outline" onclick="render()">Cancelar</button></div><div class="grid2"><div class="field"><label>Nome / título</label><input id="spName" value="${esc(s.name)}"></div><div class="field"><label>Data e horário</label><input id="spDate" value="${esc(s.date)}"></div><div class="field"><label>Mensagem curta</label><input id="spNote" value="${esc(s.note)}"></div><div class="field"><label>Arquivo de imagem</label><div class="upload-line"><input id="spFile" type="file" accept="image/*"><span class="hint">ou use uma imagem já existente</span></div><input id="spImage" value="${esc(s.image)}" placeholder="ex.: cei-palavra.jpg"></div></div><div class="preview" style="margin-top:16px"><div class="preview-card"><div class="thumb" id="spPreviewThumb">CEI</div><div><div class="hint">Prévia</div><strong id="spPreviewName">${esc(s.name||'Novo pregador')}</strong><div class="hint" id="spPreviewDate">${esc(s.date)}</div></div></div></div><div class="toolbar" style="margin-top:18px"><button class="save" onclick="saveSpeaker()">Salvar pregador</button></div></div>`;document.getElementById('spName').oninput=e=>document.getElementById('spPreviewName').textContent=e.target.value||'Novo pregador';document.getElementById('spDate').oninput=e=>document.getElementById('spPreviewDate').textContent=e.target.value;document.getElementById('spFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{document.getElementById('spPreviewThumb').innerHTML=`<img src="${reader.result}" style="width:92px;height:76px;object-fit:cover;border-radius:10px">`;document.getElementById('spImage').value=reader.result};reader.readAsDataURL(file)}}
window.saveSpeaker=()=>{const obj={id:editIndex===null?crypto.randomUUID?.()||Date.now().toString():state.speakers[editIndex].id,name:spName.value,date:spDate.value,note:spNote.value,image:spImage.value,active:editIndex===null?true:state.speakers[editIndex].active};if(editIndex===null)state.speakers.push(obj);else state.speakers[editIndex]=obj;persist();toast('Pregador salvo.');render()}
window.toggleSpeaker=i=>{state.speakers[i].active=!state.speakers[i].active;persist();render()};window.moveSpeaker=(i,d)=>{const j=i+d;if(j<0||j>=state.speakers.length)return;[state.speakers[i],state.speakers[j]]=[state.speakers[j],state.speakers[i]];persist();render()};window.removeSpeaker=i=>{if(confirm('Excluir este pregador?')){state.speakers.splice(i,1);persist();render()}};
function services(p){p.innerHTML=`<div class="toolbar"><div><h2>Cultos e encontros</h2><div class="hint">Crie quantos horários precisar.</div></div><button class="save" onclick="newService()">+ Novo culto</button></div><div class="card">${state.services.length?state.services.map((s,i)=>`<div class="row"><div><b>${esc(s.title)}</b><small>${esc(s.day)} • ${esc(s.time)} • ${esc(s.location)} • ${s.active?'Visível':'Oculto'}</small><small>${esc(s.description)}</small></div><div class="row-actions"><button class="mini" onclick="editService(${i})">Editar</button><button class="mini" onclick="toggleService(${i})">${s.active?'Ocultar':'Ativar'}</button><button class="mini danger" onclick="removeService(${i})">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhum culto cadastrado.</div>'}</div>`}
window.newService=()=>{editIndex=null;openServiceForm()};window.editService=i=>{editIndex=i;openServiceForm(state.services[i])};
function openServiceForm(s={day:'DOMINGO',time:'18:00',title:'',description:'',location:'CEI Barra',active:true}){const p=document.getElementById('panel');p.innerHTML=`<div class="card"><div class="toolbar"><h2>${editIndex===null?'Novo culto':'Editar culto'}</h2><button class="outline" onclick="render()">Cancelar</button></div><div class="grid2"><div class="field"><label>Dia</label><input id="svDay" value="${esc(s.day)}"></div><div class="field"><label>Horário</label><input id="svTime" value="${esc(s.time)}"></div><div class="field"><label>Título</label><input id="svTitle" value="${esc(s.title)}"></div><div class="field"><label>Local</label><input id="svLocation" value="${esc(s.location)}"></div><div class="field" style="grid-column:1/-1"><label>Descrição</label><textarea id="svDescription">${esc(s.description)}</textarea></div></div><div class="toolbar" style="margin-top:18px"><button class="save" onclick="saveService()">Salvar culto</button></div></div>`}
window.saveService=()=>{const obj={id:editIndex===null?Date.now().toString():state.services[editIndex].id,day:svDay.value,time:svTime.value,title:svTitle.value,description:svDescription.value,location:svLocation.value,active:editIndex===null?true:state.services[editIndex].active};if(editIndex===null)state.services.push(obj);else state.services[editIndex]=obj;persist();render()};window.toggleService=i=>{state.services[i].active=!state.services[i].active;persist();render()};window.removeService=i=>{if(confirm('Excluir este culto?')){state.services.splice(i,1);persist();render()}};
function events(p){p.innerHTML=`<div class="toolbar"><div><h2>Eventos</h2><div class="hint">Cadastre os próximos encontros especiais.</div></div><button class="save" onclick="newEvent()">+ Novo evento</button></div><div class="card">${state.events.length?state.events.map((e,i)=>`<div class="row"><div><b>${esc(e.title)}</b><small>${esc(e.day)} ${esc(e.month)} • ${e.active?'Visível':'Oculto'}</small><small>${esc(e.description)}</small></div><div class="row-actions"><button class="mini" onclick="editEvent(${i})">Editar</button><button class="mini" onclick="toggleEvent(${i})">${e.active?'Ocultar':'Ativar'}</button><button class="mini danger" onclick="removeEvent(${i})">Excluir</button></div></div>`).join(''):'<div class="empty">Nenhum evento cadastrado.</div>'}</div>`}
window.newEvent=()=>{editIndex=null;openEventForm()};window.editEvent=i=>{editIndex=i;openEventForm(state.events[i])};
function openEventForm(e={day:'01',month:'NOV',title:'',description:'',active:true}){document.getElementById('panel').innerHTML=`<div class="card"><div class="toolbar"><h2>${editIndex===null?'Novo evento':'Editar evento'}</h2><button class="outline" onclick="render()">Cancelar</button></div><div class="grid2"><div class="field"><label>Dia</label><input id="evDay" value="${esc(e.day)}"></div><div class="field"><label>Mês</label><input id="evMonth" value="${esc(e.month)}"></div><div class="field"><label>Título</label><input id="evTitle" value="${esc(e.title)}"></div><div class="field"><label>Descrição</label><input id="evDescription" value="${esc(e.description)}"></div></div><div class="toolbar" style="margin-top:18px"><button class="save" onclick="saveEvent()">Salvar evento</button></div></div>`}
window.saveEvent=()=>{const obj={id:editIndex===null?Date.now().toString():state.events[editIndex].id,day:evDay.value,month:evMonth.value,title:evTitle.value,description:evDescription.value,active:editIndex===null?true:state.events[editIndex].active};if(editIndex===null)state.events.push(obj);else state.events[editIndex]=obj;persist();render()};window.toggleEvent=i=>{state.events[i].active=!state.events[i].active;persist();render()};window.removeEvent=i=>{if(confirm('Excluir este evento?')){state.events.splice(i,1);persist();render()}};
function prayers(p){const req=JSON.parse(localStorage.getItem('cei-barra-prayer-requests')||'[]');p.innerHTML=`<div class="card"><div class="toolbar"><div><h2>Pedidos de oração</h2><div class="hint">Mensagens recebidas pelo formulário da home.</div></div><button class="outline danger" onclick="clearPrayers()">Limpar pedidos</button></div>${req.length?req.map((r,i)=>`<div class="prayer"><b>${esc(r.name||'Sem nome')}</b><small>${new Date(r.createdAt).toLocaleString('pt-BR')} • ${esc(r.contact||'Sem contato')}</small><p>${esc(r.message)}</p></div>`).join(''):'<div class="empty">Nenhum pedido recebido.</div>'}</div>`}
window.clearPrayers=()=>{if(confirm('Apagar todos os pedidos deste navegador?')){localStorage.removeItem('cei-barra-prayer-requests');render()}};
function backup(p){p.innerHTML=`<div class="grid2"><div class="card"><h2>Exportar conteúdo</h2><p>Baixe um arquivo JSON com pregadores, cultos, eventos e links.</p><button class="save" onclick="exportData()">Baixar backup</button></div><div class="card"><h2>Importar conteúdo</h2><p>Restaure um backup feito por este painel.</p><input id="importFile" type="file" accept="application/json"><div class="toolbar" style="margin-top:14px"><button class="outline" onclick="importData()">Importar arquivo</button></div></div></div><div class="card" style="margin-top:16px"><h2>Resetar demo</h2><p class="hint">Volta os dados do painel para um conjunto básico de exemplo.</p><button class="outline danger" onclick="resetData()">Resetar</button></div>`}
window.exportData=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cei-barra-backup.json';a.click();URL.revokeObjectURL(a.href)};window.importData=()=>{const f=document.getElementById('importFile').files[0];if(!f)return alert('Selecione um arquivo JSON.');const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);persist();render();toast('Backup importado.')}catch{alert('Arquivo inválido.')}};r.readAsText(f)};window.resetData=()=>{if(confirm('Resetar todo o conteúdo deste navegador?')){localStorage.removeItem(KEY);state=load();render()}};window.switchTab=t=>{tab=t;render()};render();
