const DEFAULT={services:[{day:'DOMINGO',time:'18:00',title:'Culto de Celebração',description:'Um tempo de louvor, Palavra e comunhão para toda a família.',location:'CEI Barra',active:true},{day:'QUARTA',time:'19:30',title:'Culto da Palavra',description:'Uma noite para aprofundar a fé e crescer no conhecimento da Palavra.',location:'CEI Barra',active:true},{day:'SEXTA',time:'19:30',title:'Encontro de Oração',description:'Momento de intercessão, cuidado e busca pela presença de Deus.',location:'CEI Barra',active:true}],events:[{date:'18',month:'OUT',title:'Celebração em família',description:'Uma noite especial de louvor e comunhão. Acompanhe os avisos nos canais oficiais.',image:'cei-celebracao.jpg',active:true},{date:'25',month:'OUT',title:'Encontro da comunidade',description:'Um momento para estar juntos, compartilhar e fortalecer vínculos.',image:'cei-mulheres.jpg',active:true}]};
function getData(){try{const x=JSON.parse(localStorage.getItem('cei-barra-content-v3')||'{}');return {...DEFAULT,...x,services:Array.isArray(x.services)?x.services:DEFAULT.services,events:Array.isArray(x.events)?x.events:DEFAULT.events}}catch{return DEFAULT}}
const d=getData();
const activeServices=d.services.filter(x=>x.active); const activeEvents=d.events.filter(x=>x.active);
document.getElementById('services').innerHTML=activeServices.map(s=>`<article class="service"><span class="day">${s.day}</span><h3>${s.title}</h3><div class="time">${s.time}</div><p>${s.description}</p><div class="place">${s.location}</div></article>`).join('')||'<p>Programação em atualização.</p>';
document.getElementById('events').innerHTML=activeEvents.map(e=>`<article class="event"><img src="./images/${e.image}" alt=""><div class="eventBody"><div class="eventDate"><span>${e.month}</span><b>${e.date}</b></div><h3>${e.title}</h3><p>${e.description}</p></div></article>`).join('')||'<p>Nenhum evento cadastrado.</p>';
if(activeServices[0]){document.getElementById('heroNext').textContent=`${activeServices[0].day[0]+activeServices[0].day.slice(1).toLowerCase()} · ${activeServices[0].time}`;document.getElementById('heroNextTitle').textContent=activeServices[0].title}
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('menu').addEventListener('click',()=>document.getElementById('nav').classList.toggle('open'));
document.getElementById('prayerForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const requests=JSON.parse(localStorage.getItem('cei-barra-prayer-requests')||'[]');requests.unshift({id:Date.now().toString(),name:fd.get('name'),contact:fd.get('contact'),message:fd.get('message'),createdAt:new Date().toISOString(),read:false});localStorage.setItem('cei-barra-prayer-requests',JSON.stringify(requests));e.currentTarget.reset();document.getElementById('prayerSuccess').textContent='Seu pedido foi registrado. Recebemos sua mensagem com carinho.';});
