import { useMemo, useState } from 'react';
import { CalendarDays, Check, FileDown, Heart, Home, Image, LogOut, Plus, RotateCcw, Save, Settings, Trash2, Users, X } from 'lucide-react';
import { defaultContent, loadContent, resetContent, saveContent, type EventItem, type Service, type SiteContent } from './content';

const adminKey = 'cei-barra-admin-session-v1';
const requestsKey = 'cei-barra-prayer-requests';

export default function Admin() {
  const [logged, setLogged] = useState(() => sessionStorage.getItem(adminKey) === '1');
  const [content, setContent] = useState<SiteContent>(() => loadContent());
  const [tab, setTab] = useState('dashboard');
  const [message, setMessage] = useState('');
  const [requests, setRequests] = useState<any[]>(() => JSON.parse(localStorage.getItem(requestsKey) || '[]'));
  const save = () => { saveContent(content); setMessage('Alterações salvas neste navegador.'); window.setTimeout(() => setMessage(''), 2500); };
  const exportData = () => { const payload = JSON.stringify({ content, prayerRequests: requests }, null, 2); const blob = new Blob([payload], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'cei-barra-backup.json'; a.click(); URL.revokeObjectURL(url); };
  if (!logged) return <AdminLogin onLogin={() => { sessionStorage.setItem(adminKey, '1'); setLogged(true); }} />;

  const unread = requests.filter(r => !r.read).length;
  const activeServices = content.services.filter(s => s.active).length;
  const activeEvents = content.events.filter(e => e.active).length;
  const nav = [
    ['dashboard', 'Visão geral', Home],
    ['home', 'Página inicial', Home],
    ['services', 'Programação', CalendarDays],
    ['events', 'Eventos', CalendarDays],
    ['prayer', `Pedidos de oração${unread ? ` (${unread})` : ''}`, Heart],
    ['settings', 'Configurações', Settings],
  ] as const;
  return <div className="admin-shell">
    <aside className="admin-sidebar"><div className="admin-logo"><img src={`${import.meta.env.BASE_URL}images/cei-barra-logo.png`} alt="CEI Barra"/><span><strong>CEI Barra</strong><small>Painel administrativo</small></span></div><nav>{nav.map(([id,label,Icon]) => <button className={tab===id?'active':''} key={id} onClick={() => setTab(id)}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="admin-side-bottom"><a href="./"><Home size={16}/> Ver site</a><button onClick={() => { sessionStorage.removeItem(adminKey); setLogged(false); }}><LogOut size={16}/> Sair</button></div></aside>
    <div className="admin-main"><header className="admin-top"><div><span className="admin-eyebrow">PAINEL DA IGREJA</span><h1>{nav.find(n => n[0]===tab)?.[1]}</h1></div><div className="admin-top-actions"><span>{message}</span><button onClick={save}><Save size={16}/> Salvar</button></div></header>
      <div className="admin-content">
        {tab==='dashboard' && <Dashboard content={content} requests={requests} setTab={setTab} activeServices={activeServices} activeEvents={activeEvents}/>} 
        {tab==='home' && <HomeEditor content={content} setContent={setContent}/>} 
        {tab==='services' && <ServicesEditor services={content.services} onChange={(services) => setContent({...content, services})}/>} 
        {tab==='events' && <EventsEditor events={content.events} onChange={(events) => setContent({...content, events})}/>} 
        {tab==='prayer' && <PrayerInbox requests={requests} setRequests={(next) => { setRequests(next); localStorage.setItem(requestsKey, JSON.stringify(next)); }}/>} 
        {tab==='settings' && <SettingsEditor content={content} setContent={setContent} exportData={exportData} reset={() => { resetContent(); setContent(defaultContent); setMessage('Conteúdo restaurado.'); }}/>} 
      </div>
    </div>
  </div>;
}

function AdminLogin({ onLogin }: { onLogin: () => void }) { const [user,setUser]=useState(''); const [pass,setPass]=useState(''); const [error,setError]=useState(''); const submit=(e:React.FormEvent)=>{e.preventDefault(); if((user==='admin'||user==='ceiadmin')&&pass==='cei2026'){onLogin();}else setError('Acesso de demonstração: use admin / cei2026');}; return <div className="admin-login"><div className="admin-login-card"><img src={`${import.meta.env.BASE_URL}images/cei-barra-logo.png`} alt="CEI Barra"/><span className="admin-eyebrow">ÁREA ADMINISTRATIVA</span><h1>Entrar no painel</h1><p>Gerencie o conteúdo da página, programação e pedidos de oração.</p><form onSubmit={submit}><label>Usuário<input value={user} onChange={e=>setUser(e.target.value)} placeholder="admin"/></label><label>Senha<input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="••••••••"/></label>{error && <div className="admin-error">{error}</div>}<button className="admin-primary" type="submit">Entrar</button></form><small>Protótipo local para GitHub Pages. A autenticação real deve ser feita com backend.</small></div></div> }

function Dashboard({content,requests,setTab,activeServices,activeEvents}:{content:SiteContent;requests:any[];setTab:(s:string)=>void;activeServices:number;activeEvents:number}) { const unread=requests.filter(r=>!r.read).length; return <><div className="dashboard-welcome"><div><span className="admin-eyebrow">BEM-VINDO</span><h2>Olá, equipe CEI Barra.</h2><p>Este painel organiza os principais conteúdos do site em um só lugar.</p></div><img src={`${import.meta.env.BASE_URL}images/cei-interior.jpg`} alt="Interior da CEI Barra"/></div><div className="stat-grid"><Stat icon={CalendarDays} label="Horários ativos" value={activeServices}/><Stat icon={CalendarDays} label="Eventos ativos" value={activeEvents}/><Stat icon={Heart} label="Pedidos novos" value={unread}/><Stat icon={Users} label="Seções" value="06"/></div><div className="admin-panels"><div className="admin-panel"><div className="panel-head"><div><span className="admin-eyebrow">ATENÇÃO</span><h3>Pedidos de oração</h3></div><button onClick={()=>setTab('prayer')}>Abrir caixa →</button></div>{requests.slice(0,4).map(r=><div className="mini-request" key={r.id}><span className={r.read?'read-dot':'new-dot'}></span><div><strong>{r.name || 'Sem nome'}</strong><p>{String(r.message || '').slice(0,96)}</p></div><small>{new Date(r.createdAt).toLocaleDateString('pt-BR')}</small></div>)}{requests.length===0 && <p className="empty">Nenhum pedido recebido neste navegador.</p>}</div><div className="admin-panel"><div className="panel-head"><div><span className="admin-eyebrow">ATALHOS</span><h3>Editar o site</h3></div></div><button className="shortcut" onClick={()=>setTab('home')}><Image size={17}/><span>Hero e apresentação<small>Textos, fotos e links</small></span></button><button className="shortcut" onClick={()=>setTab('services')}><CalendarDays size={17}/><span>Programação<small>Dias, horários e descrição</small></span></button><button className="shortcut" onClick={()=>setTab('events')}><CalendarDays size={17}/><span>Eventos<small>Agenda e imagens</small></span></button></div></div></> }

function Stat({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <div className="stat-card"><span><Icon size={17}/></span><div><small>{label}</small><strong>{value}</strong></div></div>}

function HomeEditor({content,setContent}:{content:SiteContent;setContent:(c:SiteContent)=>void}) { const update=(key:keyof SiteContent,value:any)=>setContent({...content,[key]:value}); return <div className="editor-stack"><EditorCard title="Apresentação" subtitle="O conteúdo principal da primeira tela."><Field label="Título principal"><textarea value={content.heroTitle} onChange={e=>update('heroTitle',e.target.value)}/></Field><Field label="Texto de apoio"><textarea value={content.heroText} onChange={e=>update('heroText',e.target.value)}/></Field><Field label="Imagem principal"><select value={content.heroImage} onChange={e=>update('heroImage',e.target.value)}>{['cei-interior.jpg','cei-culto-comunidade.jpg','cei-celebracao.jpg'].map(v=><option key={v}>{v}</option>)}</select></Field></EditorCard><EditorCard title="A Igreja" subtitle="Texto e foto da seção institucional."><Field label="Título"><input value={content.welcomeTitle} onChange={e=>update('welcomeTitle',e.target.value)}/></Field><Field label="Texto"><textarea value={content.welcomeText} onChange={e=>update('welcomeText',e.target.value)}/></Field><Field label="Imagem"><select value={content.welcomeImage} onChange={e=>update('welcomeImage',e.target.value)}>{['cei-culto-comunidade.jpg','cei-interior.jpg','cei-palavra.jpg','cei-mulheres.jpg'].map(v=><option key={v}>{v}</option>)}</select></Field></EditorCard><EditorCard title="Canais e contato" subtitle="Informações usadas no rodapé e no contato."><div className="field-grid"><Field label="Endereço"><input value={content.address} onChange={e=>update('address',e.target.value)}/></Field><Field label="Cidade / estado"><input value={content.city} onChange={e=>update('city',e.target.value)}/></Field><Field label="Telefone"><input value={content.phone} onChange={e=>update('phone',e.target.value)}/></Field><Field label="E-mail"><input value={content.email} onChange={e=>update('email',e.target.value)}/></Field><Field label="Instagram"><input value={content.instagram} onChange={e=>update('instagram',e.target.value)}/></Field><Field label="YouTube"><input value={content.youtube} onChange={e=>update('youtube',e.target.value)}/></Field></div></EditorCard></div> }

function ServicesEditor({services,onChange}:{services:Service[];onChange:(s:Service[])=>void}){ const add=()=>onChange([...services,{id:crypto.randomUUID(),day:'DOMINGO',time:'19:00',title:'Novo encontro',description:'Descreva este encontro.',location:'CEI Barra',active:true}]); return <div className="editor-stack"><EditorCard title="Programação" subtitle="Cadastre os encontros que aparecem na página inicial."><div className="toolbar"><button className="admin-primary small" onClick={add}><Plus size={15}/> Novo horário</button></div>{services.map((s,i)=><div className="repeater" key={s.id}><div className="repeater-head"><strong>{s.title || 'Novo horário'}</strong><div><label className="switch"><input type="checkbox" checked={s.active} onChange={e=>{const n=[...services];n[i]={...s,active:e.target.checked};onChange(n)}}/><span/></label><button className="icon-danger" onClick={()=>onChange(services.filter(x=>x.id!==s.id))}><Trash2 size={15}/></button></div></div><div className="field-grid four"><Field label="Dia"><input value={s.day} onChange={e=>{const n=[...services];n[i]={...s,day:e.target.value};onChange(n)}}/></Field><Field label="Horário"><input value={s.time} onChange={e=>{const n=[...services];n[i]={...s,time:e.target.value};onChange(n)}}/></Field><Field label="Nome"><input value={s.title} onChange={e=>{const n=[...services];n[i]={...s,title:e.target.value};onChange(n)}}/></Field><Field label="Local"><input value={s.location} onChange={e=>{const n=[...services];n[i]={...s,location:e.target.value};onChange(n)}}/></Field></div><Field label="Descrição"><textarea value={s.description} onChange={e=>{const n=[...services];n[i]={...s,description:e.target.value};onChange(n)}}/></Field></div>)}</EditorCard></div> }

function EventsEditor({events,onChange}:{events:EventItem[];onChange:(e:EventItem[])=>void}){ const add=()=>onChange([...events,{id:crypto.randomUUID(),date:'01',month:'NOV',title:'Novo evento',description:'Descrição do evento.',image:'cei-galeria.jpg',active:true}]); return <div className="editor-stack"><EditorCard title="Eventos" subtitle="Mantenha a agenda da igreja sempre atualizada."><div className="toolbar"><button className="admin-primary small" onClick={add}><Plus size={15}/> Novo evento</button></div>{events.map((e,i)=><div className="repeater" key={e.id}><div className="repeater-head"><strong>{e.title || 'Novo evento'}</strong><div><label className="switch"><input type="checkbox" checked={e.active} onChange={ev=>{const n=[...events];n[i]={...e,active:ev.target.checked};onChange(n)}}/><span/></label><button className="icon-danger" onClick={()=>onChange(events.filter(x=>x.id!==e.id))}><Trash2 size={15}/></button></div></div><div className="field-grid four"><Field label="Dia"><input value={e.date} onChange={ev=>{const n=[...events];n[i]={...e,date:ev.target.value};onChange(n)}}/></Field><Field label="Mês"><input value={e.month} onChange={ev=>{const n=[...events];n[i]={...e,month:ev.target.value};onChange(n)}}/></Field><Field label="Título"><input value={e.title} onChange={ev=>{const n=[...events];n[i]={...e,title:ev.target.value};onChange(n)}}/></Field><Field label="Imagem"><select value={e.image} onChange={ev=>{const n=[...events];n[i]={...e,image:ev.target.value};onChange(n)}}>{['cei-galeria.jpg','cei-celebracao.jpg','cei-mulheres.jpg','cei-palavra.jpg'].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label="Descrição"><textarea value={e.description} onChange={ev=>{const n=[...events];n[i]={...e,description:ev.target.value};onChange(n)}}/></Field></div>)}</EditorCard></div> }

function PrayerInbox({requests,setRequests}:{requests:any[];setRequests:(r:any[])=>void}) { const remove=(id:string)=>setRequests(requests.filter(r=>r.id!==id)); const read=(id:string)=>setRequests(requests.map(r=>r.id===id?{...r,read:true}:r)); return <div className="editor-stack"><EditorCard title="Pedidos de oração" subtitle="Mensagens recebidas pelo formulário desta instalação."><div className="inbox-tools"><span>{requests.length} pedido(s)</span><button className="ghost-action" onClick={()=>setRequests([])}><Trash2 size={15}/> Limpar todos</button></div>{requests.map(r=><article className={`prayer-inbox ${r.read?'read':''}`} key={r.id}><div className="prayer-head"><div><strong>{r.name||'Sem nome'}</strong><span>{new Date(r.createdAt).toLocaleString('pt-BR')}</span></div><div><button className="ghost-action" onClick={()=>read(r.id)}><Check size={15}/> Marcar lido</button><button className="icon-danger" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></div></div><p>{r.message}</p>{r.contact && <small>Contato: {r.contact}</small>}</article>)}{requests.length===0 && <div className="empty-state"><Heart size={24}/><h3>Caixa vazia</h3><p>Os pedidos enviados pelo site aparecerão aqui.</p></div>}</EditorCard></div> }

function SettingsEditor({content,setContent,exportData,reset}:{content:SiteContent;setContent:(c:SiteContent)=>void;exportData:()=>void;reset:()=>void}) { return <div className="editor-stack"><EditorCard title="Configurações" subtitle="Ferramentas do conteúdo local."><div className="settings-actions"><button className="admin-primary" onClick={exportData}><FileDown size={16}/> Exportar backup JSON</button><button className="ghost-action" onClick={reset}><RotateCcw size={15}/> Restaurar conteúdo padrão</button></div><div className="admin-note"><Check size={18}/><div><strong>Como este painel funciona</strong><p>Os dados são gravados no localStorage deste navegador. Isso permite testar e administrar a interface no GitHub Pages, mas não cria um banco compartilhado entre os administradores.</p></div></div></EditorCard><EditorCard title="Próximo passo para produção" subtitle="Quando você quiser transformar o painel em uma área administrativa real."><div className="production-list"><div><span>01</span><strong>Autenticação real</strong><p>Supabase Auth, Firebase Auth ou WordPress.</p></div><div><span>02</span><strong>Banco de dados</strong><p>Serviços, eventos e pedidos compartilhados.</p></div><div><span>03</span><strong>Upload de imagens</strong><p>Biblioteca de mídia para trocar fotos sem editar código.</p></div></div></EditorCard></div> }

function EditorCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}) { return <section className="editor-card"><div className="editor-head"><div><span className="admin-eyebrow">EDITOR</span><h2>{title}</h2><p>{subtitle}</p></div></div>{children}</section> }
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="admin-field"><span>{label}</span>{children}</label>}
